#!/usr/bin/env bash
# leaf-to-resource-map.csv 의 각 행에 대해 leaf/imports.tf 를 생성
# 카탈로그 패턴 매칭은 단순화: tf_address 컬럼이 채워져 있어야 함
set -euo pipefail

MAP="$IMPORT_DOC_DIR/leaf-to-resource-map.csv"

# CSV 헤더 스킵하고 행 순회 (tf_address, resource_id 채워진 행만)
tail -n +2 "$MAP" | while IFS=',' read -r leaf addr rid notes; do
  if [[ -z "$addr" || -z "$rid" ]]; then
    echo "[skip] $leaf (tf_address or resource_id empty)"
    continue
  fi
  TARGET="$REPO_ROOT/$leaf/imports.tf"
  # 동일 leaf에 여러 import이 있는 경우 같은 파일에 누적 작성
  if [[ ! -f "$TARGET" ]]; then
    echo "# Generated by scripts/import/generate-imports.sh — remove after apply" > "$TARGET"
  fi
  cat >> "$TARGET" <<EOF

import {
  id = "$rid"
  to = $addr
}
EOF
  echo "[gen] $leaf"
done
